version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:   
    - cypress/install
    - cypress/run:
        requires:
        - cypress/install
        CYPRESS_RECORD_KEY: 7bb5cd43-7ae4-4c31-bdb2-91b0da5c2b9c
        record: true
        parallel: true
        parallelism: 4

